### ISSUE TITLE
proverDeleteCredentials is breaking the App

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/indy-sdk-react-native#29] opened 2022-01-10 17:39 UTC
This commit
#26 
is breaking the App, 
the function proverDeleteCredentials is not available in Indy.framework, at least the version that is being used on Bifold
So either update the framework or remove that function

![Screen Shot 2022-01-10 at 12 37 43 PM](https://user-images.githubusercontent.com/46829557/148812670-f58d3f26-4c82-48b8-9cd6-b24b6cafb32e.png)

**Comment by TimoGlastra** [comment] 2022-01-12 18:07
Issue caused by outdated Indy.Framework build, so closing this issue

**Closed as completed** 2022-01-12 18:07 UTC

**Comment by TimoGlastra** [comment] 2022-01-12 18:08
If anyone else encounters this issue, please replace the Indy.Framework in your ios/Pods/Frameworks with the one from this PR: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/170
